language: c

install:
 - sudo apt-get update
 - sudo apt-get install gstreamer0.10-tools gstreamer0.10-plugins-base
       gstreamer0.10-plugins-good gstreamer0.10-plugins-bad
       python-gst0.10 python-opencv python-numpy
       python-docutils python-nose pep8 pylint expect
       gstreamer0.10-x xvfb
 - make

script:
 - xvfb-run -s "-screen 0 1024x768x24" make check
